### ISSUE TITLE
Module For QUANT HD USER FACING

### ISSUE THREAD

**Issue by dmitriyprime** [PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux#1]
Hi! Could you please help me? My laptop is Acer Nitro 17 with Ubuntu 22.04 installed. I have run you script to fix the problem with camera that doesn't work and have this error during enabling service - 

### Module For QUANT HD USER FACING BY @Prabhat_Proxy ###
     Special Thanks to Giuliano69 for the driver :)

building

make: Entering directory '/usr/src/linux-headers-6.5.0-26-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
make: Leaving directory '/usr/src/linux-headers-6.5.0-26-generic'
Compiled Successfully
copying module to root.

[sudo] password for dmitriyprime: 

2) copying service to systemd.

3) enabling service.
Job for loaduvc.service failed because the control process exited with error code.
See "systemctl status loaduvc.service" and "journalctl -xeu loaduvc.service" for details.

![image](https://github.com/PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux/assets/17761633/2b58409a-bc8a-4ef6-b787-fdaff18099b9)

![image](https://github.com/PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux/assets/17761633/97ace944-d40e-408e-9aff-1abf9f1bd5ba)

**Comment by PrabhatProxy** [comment]
Did you face any error while building?
Or can you build it clean and send the output of terminal?

**Comment by fus0g** [comment]
Is your secure boot enabled?
If yes then try disabling it and try again.

**Comment by a0x14D** [comment]
i have also same issue but i use  i3 window mangers so its not a big problam   
run manually 
```
sudo loaduvc.sh
```
check onece if it works then add to ~/.profile  or ~/xprofile  something check google

**Comment by TheAthleticCoder** [comment]
Hey!
When i execute the script, the same error occurs as shown below:

![Screenshot from 2024-04-12 11-30-38](https://github.com/PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux/assets/55716761/4a1d06a1-5940-4cd8-be0d-c36dc25153ef)

Any idea on how to fix this and get the camera working?

**Comment by fus0g** [comment]
Disable Secure Boot and It will work!
