### ISSUE TITLE
driver not working in fedora 40 after the new kernel update

### ISSUE THREAD

**Issue by Aaditya1611** [PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux#10]
in the previous kernel version: 6.10.3-200.fc40 , it was working fine. After the update it stopped working.
current kernel version: 6.10.4-200.fc40 

output after running ./install_driver.sh :

building

make: Entering directory '/usr/src/kernels/6.10.4-200.fc40.x86_64'
make: Leaving directory '/usr/src/kernels/6.10.4-200.fc40.x86_64'
Compiled Successfully
copying module to root.

2) copying service to systemd.

3) enabling service.
Job for loaduvc.service failed because the control process exited with error code.
See "systemctl status loaduvc.service" and "journalctl -xeu loaduvc.service" for details.

The output of systemctl status loaduvc.service:

 loaduvc.service - loads custom uvc driver
     Loaded: loaded (/etc/systemd/system/loaduvc.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Thu 2024-08-15 22:08:35 IST; 3min 53s ago
    Process: 20822 ExecStart=/usr/bin/loaduvc.sh (code=exited, status=1/FAILURE)
   Main PID: 20822 (code=exited, status=1/FAILURE)
        CPU: 17ms

Aug 15 22:08:35 fedora systemd[1]: Starting loaduvc.service - loads custom uvc driver...
Aug 15 22:08:35 fedora loaduvc.sh[20823]: rmmod: ERROR: Module uvcvideo is not currently loaded
Aug 15 22:08:35 fedora loaduvc.sh[20824]: insmod: ERROR: could not insert module /usr/lib/modules/uvcvideo.ko: Invalid module format
Aug 15 22:08:35 fedora systemd[1]: loaduvc.service: Main process exited, code=exited, status=1/FAILURE
Aug 15 22:08:35 fedora systemd[1]: loaduvc.service: Failed with result 'exit-code'.
Aug 15 22:08:35 fedora systemd[1]: Failed to start loaduvc.service - loads custom uvc driver.

**Comment by fus0g** [comment]
Fixed the issue!

Reclone and install again to fix it.

**Comment by Aaditya1611** [comment]
Thanks, it works perfectly fine now.
