### ISSUE TITLE
It works perfectly on Debian 12 Sid

### ISSUE THREAD

**Issue by VanackSabbadium** [PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux#14]
...So you can update the Readme! :)
Thank you so much, it saved my life on an Acer Aspire 3 15!

**Comment by fus0g** [comment]
Thanks! Done

**Comment by jhiberne** [comment]
Debian Sid is not Debian 12. 
Debian 12 works with linux-image-6.1.xx which header miss the include `<linux/usb/uvc.h>`, so install fails.
