### ISSUE TITLE
Unable to install module on linux 6.12 on manjaro

### ISSUE THREAD

**Issue by numairfm** [PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux#16]
Works perfectly fine on kernel 6.11. I have 6.12 kernel headers installed but this message shows when I execute the install script/use make.

Module For QUANT HD USER FACING BY @Prabhat_Proxy ###
     Special Thanks to Giuliano69 for the driver :)

building

make: Entering directory '/usr/lib/modules/6.12.1-4-MANJARO/build'
  CC [M]  /home/numair/necessary/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc/uvc_driver.o
/home/numair/necessary/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc/uvc_driver.c:21:10: fatal error: asm/unaligned.h: No such file or directory
   21 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:229: /home/numair/necessary/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc/uvc_driver.o] Error 1
make[1]: *** [/usr/lib/modules/6.12.1-4-MANJARO/build/Makefile:1936: /home/numair/necessary/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/lib/modules/6.12.1-4-MANJARO/build'
failed to compile module! check docs and report any error

report any issue on github repo https://github.com/PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux/issues

**Comment by fus0g** [comment]
once check your camera is working or not as one of the 2 patches is already upstreamed in linux kernel.

**Comment by numairfm** [comment]
Good evening, the camera still seems to be broken for me on kernel 6.13 and trying to use the updated script results in this error on 6.13 and 6.12.

### Module For QUANT HD USER FACING BY @Prabhat_Proxy ###
     Special Thanks to Giuliano69 for the driver :)

building

make: Entering directory '/usr/lib/modules/6.12.1-4-MANJARO/build'
  CC [M]  /home/numair/Necessary/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc/uvc_driver.o
/home/numair/Necessary/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc/uvc_driver.c:23:5: warning: "LINUX_VERSION_CODE" is not defined, evaluates to 0 [-Wundef]
   23 | #if LINUX_VERSION_CODE < KERNEL_VERSION(6, 12, 0)
      |     ^~~~~~~~~~~~~~~~~~
/home/numair/Necessary/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc/uvc_driver.c:23:26: warning: "KERNEL_VERSION" is not defined, evaluates to 0 [-Wundef]
   23 | #if LINUX_VERSION_CODE < KERNEL_VERSION(6, 12, 0)
      |                          ^~~~~~~~~~~~~~
/home/numair/Necessary/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc/uvc_driver.c:23:40: error: missing binary operator before token "("
   23 | #if LINUX_VERSION_CODE < KERNEL_VERSION(6, 12, 0)
      |                                        ^
make[2]: *** [scripts/Makefile.build:229: /home/numair/Necessary/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc/uvc_driver.o] Error 1
make[1]: *** [/usr/lib/modules/6.12.1-4-MANJARO/build/Makefile:1936: /home/numair/Necessary/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/lib/modules/6.12.1-4-MANJARO/build'
failed to compile module! check docs and report any error

report any issue on github repo https://github.com/PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux/issues

**Comment by jkcoxson** [comment]
This is an issue I'm running into as well on the newest Pop.

**Comment by jkcoxson** [comment]
I've fixed my issue by removing the offending syntax and includes:

```
--- a/src/uvc/uvc_driver.c
+++ b/src/uvc/uvc_driver.c
@@ -20,11 +20,7 @@
 #include <linux/vmalloc.h>
 #include <linux/wait.h>
 
-#if LINUX_VERSION_CODE < KERNEL_VERSION(6, 12, 0)
 #include <asm/unaligned.h>
-#else
-#include <linux/unaligned.h>
-#endif
 
 #include <media/v4l2-common.h>
 #include <media/v4l2-ioctl.h>
diff --git a/src/uvc/uvc_video.c b/src/uvc/uvc_video.c
index 23b967c..5467560 100644
--- a/src/uvc/uvc_video.c
+++ b/src/uvc/uvc_video.c
@@ -19,11 +19,7 @@
 #include <linux/wait.h>
 #include <linux/atomic.h>
 
-#if LINUX_VERSION_CODE < KERNEL_VERSION(6, 12, 0)
 #include <asm/unaligned.h>
-#else
-#include <linux/unaligned.h>
-#endif>
 
 #include <media/v4l2-common.h>
```

**Comment by numairfm** [comment]
Thanks for the help, my camera works now!
