### ISSUE TITLE
Failed to compile module! in fedora workstation 39 

### ISSUE THREAD

**Issue by ghost** [PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux#2]
chmod +x install_driver.sh
./install_driver.sh
### Module For QUANT HD USER FACING BY @Prabhat_Proxy ###
     Special Thanks to Giuliano69 for the driver :)

building

make: Entering directory '/usr/src/kernels/6.8.6-200.fc39.x86_64'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (GCC) 13.2.1 20240316 (Red Hat 13.2.1-7)
  You are using:           
  CC [M]  /home/vatsalyavyas/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc/uvc_driver.o
/bin/sh: line 1: -Wp,-MMD,/home/vatsalyavyas/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc/.uvc_driver.o.d: No such file or directory
make[2]: *** [scripts/Makefile.build:243: /home/vatsalyavyas/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc/uvc_driver.o] Error 127
make[1]: *** [/usr/src/kernels/6.8.6-200.fc39.x86_64/Makefile:1939: /home/vatsalyavyas/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc] Error 2
make: *** [Makefile:252: __sub-make] Error 2
make: Leaving directory '/usr/src/kernels/6.8.6-200.fc39.x86_64'
failed to compile module! check docs and report any error

**Comment by fus0g** [comment]
i will fix it later , till then remove 
`CC=$COMPILER_VERSION`
from install_driver.sh and it will work

**Comment by vatsalya-vyas** [comment]
Thanks, it worked!

**Comment by ghost** [comment]
Thanks, it worked!
