### ISSUE TITLE
ERROR after installing Quanta Acer User Facing

### ISSUE THREAD

**Issue by martiangnomee** [PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux#8]
I am getting this error after following the https://github.com/fus0g/Quanta-HD-User-Facing-0x0408-0x4035_linux
after Method 1

[
**enabling service.
Job for loaduvc.service failed because the control process exited with error code.
See "systemctl status loaduvc.service" and "journalctl -xeu loaduvc.service" for details.**
]

Please can someone help, I'm not an expert

**Comment by fus0g** [comment]
give the output of "sudo systemctl status loaduvc.service"

**Comment by TheAthleticCoder** [comment]
@fus0g 
![image](https://github.com/user-attachments/assets/246f86a2-3983-4347-a957-c6b2baf45f0b)

**Comment by fus0g** [comment]
> @fus0g ![image](https://private-user-images.githubusercontent.com/55716761/348269273-246f86a2-3983-4347-a957-c6b2baf45f0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTA2NzMsIm5iZiI6MTcyMDc5MDM3MywicGF0aCI6Ii81NTcxNjc2MS8zNDgyNjkyNzMtMjQ2Zjg2YTItMzk4My00MzQ3LWE5NTctYzZiMmJhZjQ1ZjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDEzMTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYWJhYWEyMTUzNGE1YWQ1MmM1OTlkZGVjNDk3ZjdiNzk5NTIwMWUzMGVhMzAwMWEyNjZmNTQ0ZmZlMTFjOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.awoZ_5UPsgBzhtbxwOka9T9CqHc_0xKnnbWpv6nICEw)

### **Disable Secure Boot in BIOS and it will work**

**Explanation**
this module is compiled on system without any signing key so when secure boot is enabled the kernel refuses to load any unsigned module.

**Comment by anurag-choudhury** [comment]
> > @fus0g ![image](https://private-user-images.githubusercontent.com/55716761/348269273-246f86a2-3983-4347-a957-c6b2baf45f0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTA2NzMsIm5iZiI6MTcyMDc5MDM3MywicGF0aCI6Ii81NTcxNjc2MS8zNDgyNjkyNzMtMjQ2Zjg2YTItMzk4My00MzQ3LWE5NTctYzZiMmJhZjQ1ZjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDEzMTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYWJhYWEyMTUzNGE1YWQ1MmM1OTlkZGVjNDk3ZjdiNzk5NTIwMWUzMGVhMzAwMWEyNjZmNTQ0ZmZlMTFjOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.awoZ_5UPsgBzhtbxwOka9T9CqHc_0xKnnbWpv6nICEw)
> 
> ### **Disable Secure Boot in BIOS and it will work**
> **Explanation** this module is compiled on system without any signing key so when secure boot is enabled the kernel refuses to load any unsigned module.

Secure boot is already disable still it's not able to start loaduvc.service


systemctl status loaduvc.service
× loaduvc.service - loads custom uvc driver
     Loaded: loaded (/etc/systemd/system/loaduvc.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2024-07-19 23:36:31 IST; 24s ago
    Process: 6630 ExecStart=/usr/bin/loaduvc.sh (code=exited, status=1/FAILURE)
   Main PID: 6630 (code=exited, status=1/FAILURE)
        CPU: 3ms

Jul 19 23:36:31 anurag-Predator-PHN16-71 systemd[1]: Starting loads custom uvc driver...
Jul 19 23:36:31 anurag-Predator-PHN16-71 loaduvc.sh[6631]: rmmod: ERROR: Module uvcvideo is not currently lo>
Jul 19 23:36:31 anurag-Predator-PHN16-71 loaduvc.sh[6632]: insmod: ERROR: could not insert module /usr/lib/m>
Jul 19 23:36:31 anurag-Predator-PHN16-71 systemd[1]: loaduvc.service: Main process exited, code=exited, stat>
Jul 19 23:36:31 anurag-Predator-PHN16-71 systemd[1]: loaduvc.service: Failed with result 'exit-code'.
Jul 19 23:36:31 anurag-Predator-PHN16-71 systemd[1]: Failed to start loads custom uvc driver.

**Comment by anurag-choudhury** [comment]
This happening due to kernal upgrade the ucvvideo.ko is for this kernal 
vermagic:       6.5.0-35-generic 
but currently i am having kernal verision : 6.5.0-44-generic

**Comment by anurag-choudhury** [comment]
It can be fixed and back to working by installing the gcc version 12

here is how you can do it :

`sudo apt-get install gcc-12 g++-12`
 `sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 20`
`sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 20`
